version: '3'
services:
  zookeeper:
    image: qnib/plain-zookeeper
    ports:
      - "2181:2181"
  zkui:
    image: qnib/plain-zkui
    ports:
      - "9090:9090"
  broker:
    image: qnib/plain-kafka:2018-04-25_1.1.0
    hostname: "{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}"
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: '{{.Task.Slot}}'
  manager:
    image: qnib/plain-kafka-manager:2018-04-25
    ports:
      - "9000:9000"
    environment:
      ZOOKEEPER_HOSTS: "tasks.zookeeper:2181"
